REM Be sure to verify which disk this script is modifying before you run it!
Select Disk 8
CREATE PARTITION PRIMARY SIZE=10240
SELECT PARTITION 1
FORMAT FS=NTFS LABEL="Windows 11 Retail" QUICK
ACTIVE
ASSIGN LETTER=T

CREATE PARTITION PRIMARY SIZE=10240
SELECT PARTITION 2
FORMAT FS=NTFS LABEL="Windows 11 Insider Preview" QUICK
ACTIVE
ASSIGN LETTER=U

CREATE PARTITION PRIMARY SIZE=10240
SELECT PARTITION 3
FORMAT FS=NTFS LABEL="Ubuntu Linux" QUICK
ACTIVE
ASSIGN LETTER=V
REM We won't usually be making a MemTest86 partition, so this is commented out.
REM CREATE PARTITION PRIMARY SIZE=256
REM SELECT PARTITION 4
REM FORMAT FS=FAT32 LABEL="MemTest86" QUICK
REM ACTIVE
REM ASSIGN LETTER=O